---
- name: deploy vsftpd
  hosts: centos
  tasks:
  -  name: install vsftpd
     yum:  name=vsftpd
  -  name: enable vsftpd
     service: name=vsftpd enabled=true state=started
  -  name: create readme file
     copy:
       content: "welcome to this FTP server"
       dest: /var/ftp/pub/README
       force: no
       mode: 0444
...
